### PR TITLE
feat: Change handleOrderEvents to call strategy Assignment method

### PR DESCRIPTION
**Pull request by Chocksy**
Implements assignemnt handling for orders

### CODE REVIEW

**Review by ffahimi — COMMENTED** [review]
1. The assigned tag doesn't seem to hold the name of the order as it normally does in the case of assignments. The tag is similar to this " Automatic Assignment. Underlying: 146.3300:Automatic Assignment. Underlying: 146.3300""
2. There is no order in workingOrders or openPositions matching the assigned order or the other leg in the spread, they have been removed, perhaps because it is assigned or perhaps because it is expired, I am not sure.
3. I tried also using allPositions to match the position by symbol, that I could get from the orderEvent.symbol using this code, but the legs didn't have any symbols attached, and the correct position was not found, therefore at this point I gave up because I didn't know how to go forward from here:

def getPositionFromOrderEvent(self,assignment=False, symbol=None):
        if not assignment:
            orderEventId = self.orderEvent.OrderId
            order = self.context.Transactions.GetOrderById(orderEventId)
            orderTag = re.sub(" - Warning.*", "", order.Tag)

            workingOrder = self.context.workingOrders.get(orderTag)
            if workingOrder is None:
                return None

            openPosition = self.context.openPositions.get(orderTag)
            if openPosition is None:
                return None

            bookPosition = self.context.allPositions[openPosition]
            orderType = workingOrder.orderType

            return bookPosition, workingOrder, orderType
        else:
            bookPosition_legs = next((position.legs for position in self.context.allPositions.values() if any(leg.symbol == symbol.symbol for leg in position.legs)), None)
        
            bookSymbols = [leg.symbol for leg in bookPosition_legs]
            
        if not assignment:
            return bookPosition, workingOrder, orderType

**Review by ffahimi — COMMENTED** [review]
Screenshot 2024-08-25 at 10 39 46
example

**Comment by Chocksy** [comment]
@ffahimi that makes sense. I'll look into this to try and sort it out. It seems the only way is to match by symbol string. Using toString or something.

Will try and get back with some change.

**Comment by ffahimi** [comment]
thank you let me know. would be awesome to get this fixed.

**Comment by Chocksy** [comment]
@ffahimi i updated the code and now it finds the position. One thing though is that it only finds the position on the first leg being assigned. I noticed that when the second leg gets assigned the assignment method is not called. Let me know if this is a problem

**Review by ffahimi — APPROVED** [review]
Tested and works. I still had to implement the assignmenthandler in the alpha, and because the short leg is not ITM necessarily at the time of assignment, I had to monitor it in the monitor, but the functionality allows one to do that. Maybe it can be more complete, in terms of monitoring. We can add an issue.

**Pull request merged**
