### PR TITLE
serializes the positions at the EndofAlgorithm and then reads it in t…

### LINKED ISSUE #25: Store the working orders and all positions into QC storage
This should help us fix this error:
```
Runtime Error:

During the algorithm initialization, the following exception has occurred: Error getting open orders from brokerage: An existing position or open order for an unsupported security type was found: 0 . Please manually close the position or cancel the order before restarting the algorithm.An existing position or open order for an unsupported security type was found: 0 . Please manually close the position or cancel the order before restarting the algorithm. in BrokerageSetupHandler.cs:line 476 An existing position or open order for an unsupported security type was found: 0 . Please manually close the position or cancel the order before restarting the algorithm.
```

### PR DESCRIPTION
**Pull request by ffahimi**
…he Datahandler (only when using optionschainproviderfilter for the moment)

only works with slice:False
I modified the filter in order to keep the symbols that belong to the previous positions, that was stored. therefore you need to have the positions stored first. maybe that's an error that needs to be caught.

fixes #25

### CODE REVIEW

**Review by Chocksy — APPROVED** [review]
To me this seems to work well. Please @ffahimi let me know if the removal i did from DataHandler is messing up things. It it does and we do need to take the symbols and add them using `AddOptionsContracts` i would do this like this:

- in setupBaseStructure in AddUnderlying i would take all the symbols from all the legs in AllPositions but i would in a way just do it for the openPositions only
- call self.strategy.dataHandler.AddOptionContracts(symbols) to add the contracts to our universe

This should be enough.

**Comment by ffahimi** [comment]
The positions are recorded and restored. There seems to be an issue with the strategy_name sometimes coming as Order. The log as I sent on discord below, for now I added try and except around the two places the import is used in positionstore.py

During the algorithm initialization, the following exception has occurred: No module named 'Alpha.Order'
  at import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 in __init__.py: line 125
  at object_hook
    strategy_module = importlib.import_module(f'Alpha.{strategy_name}')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 in PositionsStore.py: line 100
  at raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
 in decoder.py: line 352
  at decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 in decoder.py: line 336
  at decode
    data = super().decode(json_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 in PositionsStore.py: line 136
  at load_positions
    unpacked_positions = decoder.decode(json_data)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
 in PositionsStore.py: line 155
  at Initialize
    self.positions_store.load_positions()
 in main.py: line 76
 No module named 'Alpha.Order

**Comment by ffahimi** [comment]
Second issue I see is that after restoring the positions, the quantities don't come correctly, or it could be that the positions are order quantities and not filled quantities. Look at the image, and then log of the positions below for clarification:

DEBUG -> SPXExecutionModel.Execute: SPXExecutionModel -> Execute -> allPositions: {1: Position(orderId=1, orderTag='CallCreditSpread-1', strategy=nan, strategyTag='SPXic', strategyId='CallCreditSpread', expiryStr='2024-09-16', expiry=datetime.datetime(2024, 9, 16, 0, 0), linkedOrderTag=None, targetPremium=9924.1747, orderQuantity=99, maxOrderQuantity=1, targetProfit=None, legs=[Leg(key='shortCall', expiry=None, contractSide=-1, symbol='', quantity=0, strike=5645.0, contract=None), Leg(key='longCall', expiry=None, contractSide=1, symbol='', quantity=0, strike=5655.0, contract=None)], contractSide={'SPXW 240916C05645000': -1, 'SPXW 240916C05655000': 1}, openOrder=OrderType(premium=0.0, fills=46.0, limitOrderExpiryDttm='', limitOrderPrice=1.0, bidAskSpread=0.09999999999999964, midPrice=1.1, midPriceMin=0.0, midPriceMax=1.1, limitPrice=0.0, fillPrice=1.1, openPremium=0.0, stalePrice=False, filled=False, maxLoss=-10.0, transactionIds=[1, 2], priceProgressList=[1.1]), closeOrder=OrderType(premium=0.0, fills=0, limitOrderExpiryDttm='', limitOrderPrice=0.0, bidAskSpread=0.0, midPrice=0.0, midPriceMin=0.0, midPriceMax=0.0, limitPrice=0.0, fillPrice=0.0, openPremium=0.0, stalePrice=False, filled=False, maxLoss=0.0, transactionIds=[], priceProgressList=[]), openDttm=datetime.datetime(2024, 9, 16, 10, 45, 0, 801399), openDt='2024-09-16', openDTE=0, openOrderMidPrice=1.1, openOrderMidPriceMin=1.1, openOrderMidPriceMax=1.1, openOrderBidAskSpread=0.09999999999999964, openOrderLimitPrice=1.0, openPremium=2530.0, underlyingPriceAtOpen=5615.95, openFilledDttm=0.0, openStalePrice=False, orderMidPrice=0.0, limitOrderPrice=0.0, bidAskSpread=0.0, positionPnL=0.0, closeDttm='', closeDt='', closeDTE=nan, closeOrderMidPrice=0.0, closeOrderMidPriceMin=0.0, closeOrderMidPriceMax=0.0, closeOrderBidAskSpread=nan, closeOrderLimitPrice=0.0, closePremium=0.0, underlyingPriceAtClose=nan, underlyingPriceAtOrderClose=nan, DIT=0, closeStalePrice=False, closeReason=[], PnL=2530.0, PnLMin=0.0, PnLMax=0.0, PnLMinDIT=0.0, PnLMaxDIT=0.0, orderCancelled=True, filled=False, limitOrder=True, priceProgressList=[]), 2: Position(orderId=2, orderTag='PutCreditSpread-2', strategy=nan, strategyTag='SPXic', strategyId='PutCreditSpread', expiryStr='2024-09-16', expiry=datetime.datetime(2024, 9, 16, 0, 0), linkedOrderTag=None, targetPremium=9924.1747, orderQuantity=99, maxOrderQuantity=1, targetProfit=None, legs=[Leg(key='shortPut', expiry=None, contractSide=-1, symbol='', quantity=0, strike=5585.0, contract=None), Leg(key='longPut', expiry=None, contractSide=1, symbol='', quantity=0, strike=5575.0, contract=None)], contractSide={'SPXW 240916P05585000': -1, 'SPXW 240916P05575000': 1}, openOrder=OrderType(premium=0.0, fills=132.0, limitOrderExpiryDttm='', limitOrderPrice=1.0, bidAskSpread=0.19999999999999996, midPrice=1.0499999999999998, midPriceMin=0.0, midPriceMax=1.0499999999999998, limitPrice=0.0, fillPrice=3.9999999999999996, openPremium=0.0, stalePrice=False, filled=False, maxLoss=-10.0, transactionIds=[3, 4], priceProgressList=[1.05]), closeOrder=OrderType(premium=0.0, fills=0, limitOrderExpiryDttm='', limitOrderPrice=0.0, bidAskSpread=0.0, midPrice=0.0, midPriceMin=0.0, midPriceMax=0.0, limitPrice=0.0, fillPrice=0.0, openPremium=0.0, stalePrice=False, filled=False, maxLoss=0.0, transactionIds=[], priceProgressList=[]), openDttm=datetime.datetime(2024, 9, 16, 10, 45, 0, 801399), openDt='2024-09-16', openDTE=0, openOrderMidPrice=1.05, openOrderMidPriceMin=1.05, openOrderMidPriceMax=1.05, openOrderBidAskSpread=0.19999999999999996, openOrderLimitPrice=1.0, openPremium=6600.0, underlyingPriceAtOpen=5615.95, openFilledDttm=0.0, openStalePrice=False, orderMidPrice=0.0, limitOrderPrice=0.0, bidAskSpread=0.0, positionPnL=0.0, closeDttm='', closeDt='', closeDTE=nan, closeOrderMidPrice=0.0, closeOrderMidPriceMin=0.0, closeOrderMidPriceMax=0.0, closeOrderBidAskSpread=nan, closeOrderLimitPrice=0.0, closePremium=0.0, underlyingPriceAtClose=nan, underlyingPriceAtOrderClose=nan, DIT=0, closeStalePrice=False, closeReason=[], PnL=6600.0, PnLMin=0.0, PnLMax=0.0, PnLMinDIT=0.0, PnLMaxDIT=0.0, orderCancelled=True, filled=False, limitOrder=True, priceProgressList=[])}
Screenshot 2024-09-16 at 16 54 36

**Comment by ffahimi** [comment]
Another issue I see is that (1) after restart and recovery of positions, (2) two orders from previous run were recovered, (3) then a third order is placed, which means we should be having 3 open positions in the allPositions, but the last order from the new session is not added to the dictionary, as you can see SPXW 240916P05580000 and SPXW 240916P05570000 is missing.
(See the image and log)
Screenshot 2024-09-16 at 17 07 43

	DEBUG -> SPXExecutionModel.Execute: SPXExecutionModel -> Execute -> allPositions: {1: Position(orderId=1, orderTag='CallCreditSpread-1', strategy=<Order.Order.Order object at 0x7fa57813f1d0>, strategyTag='SPXic', strategyId='CallCreditSpread', expiryStr='2024-09-16', expiry=datetime.datetime(2024, 9, 16, 0, 0), linkedOrderTag=None, targetPremium=9902.587826, orderQuantity=99, maxOrderQuantity=1, targetProfit=None, legs=[Leg(key='shortCall', expiry=datetime.datetime(2024, 9, 16, 16, 0), contractSide=-1, symbol=<QuantConnect.Symbol object at 0x7fa5e3b10600>, quantity=0, strike=5640.0, contract=<QuantConnect.Data.Market.OptionContract object at 0x7fa5781ce580>), Leg(key='longCall', expiry=datetime.datetime(2024, 9, 16, 16, 0), contractSide=1, symbol=<QuantConnect.Symbol object at 0x7fa5781cb380>, quantity=0, strike=5650.0, contract=<QuantConnect.Data.Market.OptionContract object at 0x7fa5781cc700>)], contractSide={<QuantConnect.Symbol object at 0x7fa5781ca640>: -1, <QuantConnect.Symbol object at 0x7fa5781ca480>: 1}, openOrder=OrderType(premium=0.0, fills=0, limitOrderExpiryDttm=datetime.datetime(2024, 9, 16, 11, 5, 0, 801045), limitOrderPrice=1.0, bidAskSpread=0.1499999999999997, midPrice=1.1749999999999998, midPriceMin=0.0, midPriceMax=1.1749999999999998, limitPrice=0.0, fillPrice=0.0, openPremium=0.0, stalePrice=False, filled=False, maxLoss=-10.0, transactionIds=[1, 2], priceProgressList=[1.17]), closeOrder=OrderType(premium=0.0, fills=0, limitOrderExpiryDttm='', limitOrderPrice=0.0, bidAskSpread=0.0, midPrice=0.0, midPriceMin=0.0, midPriceMax=0.0, limitPrice=0.0, fillPrice=0.0, openPremium=0.0, stalePrice=False, filled=False, maxLoss=0.0, transactionIds=[], priceProgressList=[]), openDttm=datetime.datetime(2024, 9, 16, 11, 0, 0, 801045), openDt='2024-09-16', openDTE=0, openOrderMidPrice=1.17, openOrderMidPriceMin=1.17, openOrderMidPriceMax=1.17, openOrderBidAskSpread=0.1499999999999997, openOrderLimitPrice=1.0, openPremium=0.0, underlyingPriceAtOpen=5612.17, openFilledDttm=0.0, openStalePrice=False, orderMidPrice=0.0, limitOrderPrice=0.0, bidAskSpread=0.0, positionPnL=0.0, closeDttm='', closeDt='', closeDTE=nan, closeOrderMidPrice=0.0, closeOrderMidPriceMin=0.0, closeOrderMidPriceMax=0.0, closeOrderBidAskSpread=nan, closeOrderLimitPrice=0.0, closePremium=0.0, underlyingPriceAtClose=nan, underlyingPriceAtOrderClose=nan, DIT=0, closeStalePrice=False, closeReason=[], PnL=0.0, PnLMin=0.0, PnLMax=0.0, PnLMinDIT=0.0, PnLMaxDIT=0.0, orderCancelled=True, filled=False, limitOrder=True, priceProgressList=[]), 2: Position(orderId=2, orderTag='PutCreditSpread-2', strategy=<Order.Order.Order object at 0x7fa57813f1d0>, strategyTag='SPXic', strategyId='PutCreditSpread', expiryStr='2024-09-16', expiry=datetime.datetime(2024, 9, 16, 0, 0), linkedOrderTag=None, targetPremium=9902.587826, orderQuantity=99, maxOrderQuantity=1, targetProfit=None, legs=[Leg(key='shortPut', expiry=datetime.datetime(2024, 9, 16, 16, 0), contractSide=-1, symbol=<QuantConnect.Symbol object at 0x7fa57812dc80>, quantity=0, strike=5580.0, contract=<QuantConnect.Data.Market.OptionContract object at 0x7fa5781cc300>), Leg(key='longPut', expiry=datetime.datetime(2024, 9, 16, 16, 0), contractSide=1, symbol=<QuantConnect.Symbol object at 0x7fa5e2a29f80>, quantity=0, strike=5570.0, contract=<QuantConnect.Data.Market.OptionContract object at 0x7fa5781cc2c0>)], contractSide={<QuantConnect.Symbol object at 0x7fa5781cb5c0>: -1, <QuantConnect.Symbol object at 0x7fa5781cb740>: 1}, openOrder=OrderType(premium=0.0, fills=154.0, limitOrderExpiryDttm=datetime.datetime(2024, 9, 16, 11, 5, 0, 801045), limitOrderPrice=1.0, bidAskSpread=0.1499999999999999, midPrice=0.9749999999999996, midPriceMin=0.0, midPriceMax=0.9749999999999996, limitPrice=0.0, fillPrice=3.800000000000001, openPremium=0.0, stalePrice=False, filled=False, maxLoss=-10.0, transactionIds=[3, 4], priceProgressList=[0.97]), closeOrder=OrderType(premium=0.0, fills=0, limitOrderExpiryDttm='', limitOrderPrice=0.0, bidAskSpread=0.0, midPrice=0.0, midPriceMin=0.0, midPriceMax=0.0, limitPrice=0.0, fillPrice=0.0, openPremium=0.0, stalePrice=False, filled=False, maxLoss=0.0, transactionIds=[], priceProgressList=[]), openDttm=datetime.datetime(2024, 9, 16, 11, 0, 0, 801045), openDt='2024-09-16', openDTE=0, openOrderMidPrice=0.97, openOrderMidPriceMin=0.97, openOrderMidPriceMax=0.97, openOrderBidAskSpread=0.1499999999999999, openOrderLimitPrice=1.0, openPremium=7315.000000000004, underlyingPriceAtOpen=5612.17, openFilledDttm=0.0, openStalePrice=False, orderMidPrice=0.0, limitOrderPrice=0.0, bidAskSpread=0.0, positionPnL=0.0, closeDttm='', closeDt='', closeDTE=nan, closeOrderMidPrice=0.0, closeOrderMidPriceMin=0.0, closeOrderMidPriceMax=0.0, closeOrderBidAskSpread=nan, closeOrderLimitPrice=0.0, closePremium=0.0, underlyingPriceAtClose=nan, underlyingPriceAtOrderClose=nan, DIT=0, closeStalePrice=False, closeReason=[], PnL=7315.000000000004, PnLMin=0.0, PnLMax=0.0, PnLMinDIT=0.0, PnLMaxDIT=0.0, orderCancelled=True, filled=False, limitOrder=True, priceProgressList=[])}

**Pull request merged**
